name: publish
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build & Push to Docker Hub
      uses: docker/build-push-action@v1
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "goodboyymh/no-svip-web"
        TAG_NAME: "latest"